### ISSUE TITLE
test-browser: reduce runtime

### ISSUE THREAD

**Issue by jgehrcke** [opstrace/opstrace#1087] opened 2021-07-22 11:22 UTC
from https://buildkite.com/opstrace/scheduled-main-builds/builds/2711:
```
[2021-07-22T08:48:29Z] ++ make test-browser

[2021-07-22T09:12:51Z] ++ echo '--- Exit status of make test-browser: 0'
```

`make test-browser` takes more than 20 minutes as of now. Where is it spending most of its time @terrcin and do you think we can magically speed this up by an order of magnitude? 

comparable ticket for `make test-remote/-ui`: https://github.com/opstrace/opstrace/issues/1086

**Comment by terrcin** [comment] 2021-07-23 01:34
@jgehrcke just dropping a comment saying that I've seen this, having a think. 🤔

Looking at the [latest passing main build](https://buildkite.com/opstrace/scheduled-main-builds/builds/2714) they took 25m (21%) minutes on AWS while the the complete AWS run took 1h 58m. Halving the browser test run time will not really have a meaningful impact in that case. But the browser tests in particullar will continue to be added to, so over time it may be more benefitial. What else is is happening

I still reckon we should try uping the cluster size that's built for the tests - to see what impact that has. My gut feel is that the tests are slow because the cluster is slow. If the cluster is faster we won't need it for as long so it might even be cheaper vs a longer running slow cluster. GCP and AWS run times can be quite different while the run times of test-remote and test-browser remain fairly similiar despite that. So I assume that it's alot todo with making the cluster ready to test?

Current the browser tests repeat the same small test suite againt 5 different browsers - Chromium, Firefox, WebKit, Pixel-4, & iPhone-11. I put in the mobile browser testing because I could - I'll make a branch without them to see what effect that has.

I also recently altered the way that CI runs the browser tests by making it login for each individual test rather than login once and keep that state between individual tests - making them run slower as a consequence due to doing more. This was done to help debug the timeout errors we were having - if these timeouts are primarily caused by the login white screen issue than my [attempted fix](https://github.com/opstrace/opstrace/pull/1076) for that once merged is going to allow this debugging change to be reverted. Instead of waiting I can branch #1076 now and update the tests to find out what effect this improvement will have on their run time.

**Comment by terrcin** [comment] 2021-07-23 05:11
Update:

Changing back to per worker logging in _with_ the white screen fix from https://github.com/opstrace/opstrace/pull/1076 and the browser tests now only take [4m 59s](https://buildkite.com/opstrace/prs/builds/5134#bbedccf6-45ca-46da-a1d0-7877cb803446/8288). Note: sample of 1.

**Comment by jgehrcke** [comment] 2021-07-23 10:17
> Halving the browser test run time will not really have a meaningful impact in that case

Not sure what you are implying here. the idea of that current initiative is to do high impact low effort changes everywhere, and I am confident that this will have meaningful impact overall.

> My gut feel is that the tests are slow because the cluster is slow

Hm. I am certain that the current `test-browser` runtime is dominated by 'waiting', and overhead. Not by the time it takes for individual HTTP responses to be generated. I think you've already proved that point. :)

**Comment by terrcin** [comment] 2021-07-25 02:48
> The SSO roundtrip takes O(10 s) so that really adds (and is an example for overhead, and 'waiting'). It makes a lot of sense to share the authentication state between tests. This is the kind of 'optimization' I was hoping for. Thank you!

As I said, I originally did it that way but temporarily disabled it to aid in debugging. I'm considering putting it back in.

**Closed** 2022-01-11 20:25 UTC
