### ISSUE TITLE
proposal: replace isDeepStrictEqual with something else (probably fast-deep-equal)

### ISSUE THREAD

**Issue by sreis** [opstrace/opstrace#588] opened 2021-04-22 13:46 UTC
# Problem 

The controller reconciliation loop checks if the resource spec (or some other attributes) changed and requires an update. 

Currently, we are using `isDeepStrictEqual,` but it has issues comparing an array of deeply nested objects which means some Kubernetes resources equality checks have to be written manually to compare the objects in an array. Most of them require this sort of manual equality check, and sometimes it doesn't cover all the fields in the resource. This lack of coverage leads to hard to track down bugs, like #585, because resources are not updated. 

# Proposed solution

Replace all the Kubernetes resource equality checks in the lib/kubernetes package with the functions in [`fast-deep-equal`](https://www.npmjs.com/package/fast-deep-equal) package.

**Comment by MoSattler** [comment] 2021-05-04 14:01
Hi @sreis, do you happen to have some example where `isDeepStrictEqual` caused issues, so I can develop against and assert it?

**Comment by sreis** [comment] 2021-05-04 14:32
@MoSattler A couple of examples [here](https://github.com/opstrace/opstrace/pull/587/files#diff-ff5966a0e7b247d7f2cab9af8e3a175c1d19b685471340b3d61468212012db41L64-L72) and [here](https://github.com/opstrace/opstrace/commit/fc2b42a3ef4fdeac3cf4400116abcc051b274df3#diff-ff5966a0e7b247d7f2cab9af8e3a175c1d19b685471340b3d61468212012db41).

We weren't checking all the fields in the spec so when we changed something the controller wasn't noticing that it needed to apply new changes.

Take a look at the code and tell me if we can replace all the `hasFooChanged`, for example [hasDeploymentChanged](https://github.com/opstrace/opstrace/blob/main/lib/kubernetes/src/equality/index.ts#L70), with a generic function that compares two Kubernetes resources that have a spec and an annotation field.

**Comment by MoSattler** [comment] 2021-05-06 14:33
Than you @sreis 

Do we have some example data where `isDeepStrictEqual` fails to give the correct result? 
I cannot reproduce this bug right now, but I would like to write a test, so I can assure this issue will be fixed by `fast-deep-equal`.

**Comment by sreis** [comment] 2021-05-06 14:58
@MoSattler For example, the Ingress resource [required us to compare all the elements in the array](https://github.com/opstrace/opstrace/commit/70bc254bae3b6c224dda3f5d467ece650bb3d161) otherwise, it wouldn't pick up changes to the array defining the TLS config. I can't point you to a specific change showing the TLS changes, though. We lost that history when we moved things to the public repo.

**Comment by MatApple** [comment] 2021-05-06 16:04
Hey @MoSattler the problem could best be described with a couple of generic examples.

Take the following two objects:
```
object1 = {
  A: [
    {
      foo: "bar"
    },
    {
      baz: "foobar"
    }
  ]
}

object2 = {
  A: [
    {
      baz: "foobar"
    },
     {
      foo: "bar"
    }
  ]
}
```
These two objects would be considered "equal" if they were to represent a Kubernetes spec. The ordering of the array does not matter.

Now, the problem arises when using a generic _deepEquals_ type function, because that function will say that those two objects are not equal, because `object1["A"][0] !== object2["A"][0]`.

As you might imagine, there are a number of other difficult to handle situations that can arise, for example, deep nesting of objects inside arrays.

To add more insult to the problem, Kubernetes will add default values for fields that we don't specify in the spec, in which case, a simple `deepEqual` type of check will _always_ return false because the `existing` resources will be filled with defaults that aren't present on the `desired` resources.

I have yet to find a library that will comprehensively apply a "generic" function to this problem reliably.

**Closed** 2022-01-11 20:26 UTC
Labels: thinktank: proposal
