### ISSUE TITLE
invalid response format: loki and cortex logs

### ISSUE THREAD

**Issue by terrcin** [opstrace/opstrace#1231] opened 2021-08-09 22:22 UTC
https://buildkite.com/opstrace/upgrade-tests/builds/1165#04f66c8f-cbab-4861-9bf6-ea4a2ec37086/3131-4993

```
[2021-08-09T21:36:33Z]     1) check loki ingester logs
--
  | [2021-08-09T21:36:36Z] 2021-08-09T21:36:36.804Z info: HTTP resp to GET(https://loki.system.upgrade-bk-1165-d51-a.opstrace.io/loki/api/v1/query_range?query=%7Bk8s_namespace_name%3D%22cortex%22%2C+k8s_pod_name%3D%7E%22distributor-.%2B%22%7D+%7C%3D+%22Starting+Cortex%22&direction=BACKWARD&regexp=&limit=10&start=1628184993535000000&end=1628548593535000000):
  | [2021-08-09T21:36:36Z]   status: 500
  | [2021-08-09T21:36:36Z]   body[:500]: invalid response format
  | [2021-08-09T21:36:36Z]   headers: {"date":"Mon, 09 Aug 2021 21:36:36 GMT","content-type":"application/json; charset=UTF-8","content-length":"23","connection":"close","strict-transport-security":"max-age=15724800; includeSubDomains"}
  | [2021-08-09T21:36:36Z]   totalTime: 0.056 s
  | [2021-08-09T21:36:36Z]   dnsDone->TCPconnectDone: 0.003 s
  | [2021-08-09T21:36:36Z]   connectDone->reqSent 0 s
  | [2021-08-09T21:36:36Z]   reqSent->firstResponseByte: 0.05 s
  | [2021-08-09T21:36:36Z]
  | [2021-08-09T21:36:36Z]     2) check cortex distributor logs
  | [2021-08-09T21:36:40Z] 2021-08-09T21:36:40.073Z info: HTTP resp to GET(https://loki.system.upgrade-bk-1165-d51-a.opstrace.io/loki/api/v1/query_range?query=%7Bk8s_namespace_name%3D%22system-tenant%22%2C+k8s_pod_name%3D%7E%22systemlog.*%22%7D+%7C%3D+%22following+tail+of%22&direction=BACKWARD&regexp=&limit=10&start=1628184996805000000&end=1628548596805000000):
  | [2021-08-09T21:36:40Z]   status: 500
  | [2021-08-09T21:36:40Z]   body[:500]: invalid response format
  | [2021-08-09T21:36:40Z]   headers: {"date":"Mon, 09 Aug 2021 21:36:40 GMT","content-type":"application/json; charset=UTF-8","content-length":"23","connection":"close","strict-transport-security":"max-age=15724800; includeSubDomains"}
  | [2021-08-09T21:36:40Z]   totalTime: 0.077 s
  | [2021-08-09T21:36:40Z]   dnsDone->TCPconnectDone: 0.009 s
  | [2021-08-09T21:36:40Z]   connectDone->reqSent 0 s
  | [2021-08-09T21:36:40Z]   reqSent->firstResponseByte: 0.063 s
  | [2021-08-09T21:36:40Z]
  | [2021-08-09T21:36:40Z]     3) check systemlog Fluentd instance logs
  | [2021-08-09T21:36:40Z] 2021-08-09T21:36:40.074Z info: suite teardown
  | [2021-08-09T21:36:40Z]
  | [2021-08-09T21:36:40Z]   system metrics test suite
  | [2021-08-09T21:36:40Z] 2021-08-09T21:36:40.074Z info: suite setup
  | [2021-08-09T21:36:40Z] 2021-08-09T21:36:40.074Z info: globalTestSuiteSetupOnce()
  | [2021-08-09T21:36:40Z] 2021-08-09T21:36:40.075Z info: Cortex query parameter (object):
  | [2021-08-09T21:36:40Z] {
  | [2021-08-09T21:36:40Z]   "end": "1628548600",
  | [2021-08-09T21:36:40Z]   "query": "process_cpu_seconds_total{container=\"ingester\", namespace=\"cortex\"}",
  | [2021-08-09T21:36:40Z]   "start": "1628541400",
  | [2021-08-09T21:36:40Z]   "step": "1"
  | [2021-08-09T21:36:40Z] }
  | [2021-08-09T21:36:40Z] 2021-08-09T21:36:40.075Z info: Waiting for query to return a match, deadline in 90s
  | [2021-08-09T21:36:40Z]     ✓ check if container metrics exist (151ms)
  | [2021-08-09T21:36:40Z] 2021-08-09T21:36:40.226Z info: suite teardown
```

**Comment by nickbp** [comment] 2021-08-10 01:58
The error is in a `query_range` request to loki via system-tenant.

The `invalid response format` message looks like it's coming from here and does indeed look like something internal to loki in terms of encoding a result for the HTTP response: https://github.com/grafana/loki/blob/1efeace6441b36c64d71dd9ebee39563ec6edd79/pkg/querier/queryrange/codec.go#L526

**Comment by nickbp** [comment] 2021-08-10 02:05
The [loki logs](https://buildkite.com/organizations/opstrace/pipelines/upgrade-tests/builds/1165/jobs/04f66c8f-cbab-4861-9bf6-ea4a2ec37086/artifacts/065f3476-536f-40fe-91e2-597394c3db94) have some errors around the same time that appear related:
- > level=warn ts=2021-08-09T21:36:34.679647955Z caller=logging.go:71 traceID=6b6a54ed502c9e24 orgID=system msg="GET /loki/api/v1/query_range?direction=BACKWARD&end=1628548593535000000&limit=10&query=%7Bk8s_namespace_name%3D%22cortex%22%2C+k8s_pod_name%3D~%22distributor-.%2B%22%7D+%7C%3D+%22Starting+Cortex%22&start=1628184993535000000&step=1454.000000 (500) 8.074799ms Response: \"NoSuchBucket: The specified bucket does not exist\\n\\tstatus code: 404, request id: 0XMB8ZVCJ0XA9N9M, host id: dkNVgY0m4ZP0//+bRboVLFkvUa+vE7fuEFNInDJObS1D+AqcNmdUwm14PjZTplVpY1s3iiG/aFw=\\n\" ws: false; X-Scope-Orgid: system; uber-trace-id: 6b6a54ed502c9e24:314a3cf149bccc69:3a27b8ce10fa71b5:0; "
- > level=warn ts=2021-08-09T21:36:34.692960104Z caller=logging.go:71 traceID=6b6a54ed502c9e24 orgID=system msg="GET /loki/api/v1/query_range?direction=BACKWARD&end=1628548593535000000&limit=10&query=%7Bk8s_namespace_name%3D%22cortex%22%2C+k8s_pod_name%3D~%22distributor-.%2B%22%7D+%7C%3D+%22Starting+Cortex%22&start=1628184993535000000&step=1454.000000 (500) 10.232485ms Response: \"NoSuchBucket: The specified bucket does not exist\\n\\tstatus code: 404, request id: 0XMANE8R6X87EGSN, host id: stOEobSVCYgw6m5jWQ9MmIzfSNer+sjk70mWV7qaSiu5UPg9HeD6vOfhHGuWmsKMn2VykdXwRUg=\\n\" ws: false; X-Scope-Orgid: system; uber-trace-id: 6b6a54ed502c9e24:314a3cf149bccc69:3a27b8ce10fa71b5:0; "
- (and several more)

Meanwhile the test logs show they errored out around the same time:
- > 2021-08-09T21:36:33.527Z info: HTTP resp to GET(https://loki.system.upgrade-bk-1165-d51-a.opstrace.io/loki/api/v1/query_range?query=%7Bk8s_namespace_name%3D%22loki%22%2C+k8s_container_name%3D%22ingester%22%7D+%7C%3D+%22Starting+Loki%22&direction=BACKWARD&regexp=&limit=10&start=1628184989958000000&end=1628548589958000000):
- > 2021-08-09T21:36:36.804Z info: HTTP resp to GET(https://loki.system.upgrade-bk-1165-d51-a.opstrace.io/loki/api/v1/query_range?query=%7Bk8s_namespace_name%3D%22cortex%22%2C+k8s_pod_name%3D%7E%22distributor-.%2B%22%7D+%7C%3D+%22Starting+Cortex%22&direction=BACKWARD&regexp=&limit=10&start=1628184993535000000&end=1628548593535000000):
- > 2021-08-09T21:36:40.073Z info: HTTP resp to GET(https://loki.system.upgrade-bk-1165-d51-a.opstrace.io/loki/api/v1/query_range?query=%7Bk8s_namespace_name%3D%22system-tenant%22%2C+k8s_pod_name%3D%7E%22systemlog.*%22%7D+%7C%3D+%22following+tail+of%22&direction=BACKWARD&regexp=&limit=10&start=1628184996805000000&end=1628548596805000000):

Need to check what "bucket" means real quick in the context of the loki logs.

**Comment by nickbp** [comment] 2021-08-10 06:33
From some looking around earlier, the `NoSuchBucket` error seems to be coming from an AWS library - no mention of it in the Loki code but I do see mentions of AWS. So it looks like `bucket` in this context is indeed for S3.

Maybe some loki buckets weren't set up correctly in the cluster creation, or maybe there's a problem relating to loki S3 buckets that affects upgrades? Next stop is to check the logs for bucket creation and see if anything sticks out there.

**Comment by nickbp** [comment] 2021-08-10 22:28
From early in the test log it looks like the bucket was created successfully:
```
[2021-08-09T20:54:27Z] 2021-08-09T20:54:27.982Z [34mdebug[39m: s3 bucket upgrade-bk-1165-d51-a-loki setup: cycle 2
[2021-08-09T20:54:27Z] 2021-08-09T20:54:27.986Z [34mdebug[39m: aws sdk: [AWS s3 200 0.011s 0 retries] headBucket({ Bucket: 'upgrade-bk-1165-d51-a-cortex' })
[2021-08-09T20:54:27Z] 2021-08-09T20:54:27.997Z [34mdebug[39m: aws sdk: [AWS s3 200 0.014s 0 retries] headBucket({ Bucket: 'upgrade-bk-1165-d51-a-loki' })
[2021-08-09T20:54:28Z] 2021-08-09T20:54:28.025Z [34mdebug[39m: aws sdk: [AWS s3 200 0.027s 0 retries] getBucketLifecycleConfiguration({ Bucket: 'upgrade-bk-1165-d51-a-loki' })
[2021-08-09T20:54:28Z] 2021-08-09T20:54:28.026Z [34mdebug[39m: s3 bucket upgrade-bk-1165-d51-a-loki setup: state check result: true
[2021-08-09T20:54:28Z] 2021-08-09T20:54:28.027Z [32minfo[39m: s3 bucket upgrade-bk-1165-d51-a-loki setup: reached desired state, done (duration: 1.20 s)
```

**Comment by nickbp** [comment] 2021-08-11 00:52
From looking around in the code and the rest of the test logs, I don't see anything that would explain why the S3 bucket would have disappeared on its own. It looks like it was created successfully, but then failed again with those tests.

My best guess is that the bucket happened to be cleaned up manually while the test was running? This seems more likely given that we've only had this happen once so far. As such I figure we can close this for now unless/until it recurs.

**Comment by nickbp** [comment] 2021-08-11 23:18
Yes it looks like this is the same cause as #1244. Trying to find any common pattern to the two failures...

**Comment by nickbp** [comment] 2021-08-11 23:22
The failure from #1244 is: https://buildkite.com/opstrace/upgrade-tests/builds/1169#302ab596-69dc-4784-a10b-dfe1e1ff8edd

**Comment by nickbp** [comment] 2021-08-11 23:51
From this point on I'll refer to the original failure from this ticket as 1165 and the new failure imported from #1244 as 1169.

The 1165 failure was in the `system logs test suite` in `test-remote`, while the 1169 failure had passed `test-remote`(!) and instead failed later at `test-remote-ui-api`. So this does indicate that the bucket is being somehow deleted mid-test.

The two runs both failed on main-upgrade tests on AWS, and both failed on loki buckets. However, the earlier failure was against querying loki logs in the `loki` bucket, while the later failure was against querying loki rules, which I think is in the separate `loki-config` bucket.

I checked the list of current buckets just now and saw something interesting:
```
$ aws s3 ls
[...]
2021-08-04 16:52:53 upgrade-bk--0dc-a-cortex
2021-08-04 16:52:53 upgrade-bk--0dc-a-cortex-config
2021-08-04 16:52:53 upgrade-bk--0dc-a-loki
2021-08-04 16:52:53 upgrade-bk--0dc-a-loki-config
2021-08-10 12:51:09 upgrade-bk-1166-d51-a-cortex-config
2021-08-10 12:51:09 upgrade-bk-1166-d51-a-loki
2021-08-10 16:52:48 upgrade-bk-1167-177-a-cortex-config
2021-08-10 16:52:48 upgrade-bk-1167-177-a-loki
2021-08-10 20:50:59 upgrade-bk-1168-077-a-cortex-config
2021-08-10 20:50:59 upgrade-bk-1168-077-a-loki
2021-08-11 00:52:49 upgrade-bk-1169-d5a-a-cortex-config
2021-08-11 04:52:49 upgrade-bk-1170-84f-a-cortex-config
2021-08-11 04:52:49 upgrade-bk-1170-84f-a-loki
2021-08-11 08:51:30 upgrade-bk-1171-84f-a-cortex-config
2021-08-11 08:51:30 upgrade-bk-1171-84f-a-loki
2021-08-11 12:51:13 upgrade-bk-1172-eac-a-cortex-config
2021-08-11 12:51:13 upgrade-bk-1172-eac-a-loki
2021-08-11 16:52:39 upgrade-bk-1173-eac-a-cortex-config
2021-08-11 16:52:39 upgrade-bk-1173-eac-a-loki
2021-08-11 21:10:59 upgrade-bk-1175-93c-a-cortex-config
2021-08-11 21:10:59 upgrade-bk-1175-93c-a-loki
2021-08-12 00:52:46 upgrade-bk-1176-93c-a-cortex-config
2021-08-12 00:52:46 upgrade-bk-1176-93c-a-loki
2021-08-12 04:55:18 upgrade-bk-1177-93c-a-cortex-config
2021-08-12 04:55:18 upgrade-bk-1177-93c-a-loki
2021-08-12 08:54:30 upgrade-bk-1178-3c8-a-cortex
2021-08-12 08:54:30 upgrade-bk-1178-3c8-a-cortex-config
2021-08-12 08:54:30 upgrade-bk-1178-3c8-a-loki
2021-08-12 08:54:30 upgrade-bk-1178-3c8-a-loki-config
[...]
```

Some observations from the list:
- The latest 1178 run (finished successfully a couple hours ago) still has all four buckets: `cortex`, `cortex-config`, `loki`, and `loki-config`.
- The failing 1169 only has the `cortex-config` bucket.
- All the other runs have only `loki` and `cortex-config` buckets.

The `schedul-*` and `prs-*` buckets also follow this pattern, with lots of `loki` and `cortex-config` buckets left behind, while `loki-config` and `cortex` are consistently deleted. I'm thinking that whatever's in charge of deleting these old buckets is consistently missing these leftover ones. Maybe it's also deleting more buckets than it should for these main-upgrade tests?

**Comment by nickbp** [comment] 2021-08-12 02:37
Checking the buckets again later shows that 1178's `loki-config` and `cortex` buckets were deleted and it now matches the others, while a 1179 build shows all four buckets:
```
$ aws s3 ls
2021-08-12 00:52:46 upgrade-bk-1176-93c-a-cortex-config
2021-08-12 00:52:46 upgrade-bk-1176-93c-a-loki
2021-08-12 04:55:18 upgrade-bk-1177-93c-a-cortex-config
2021-08-12 04:55:18 upgrade-bk-1177-93c-a-loki
2021-08-12 08:54:30 upgrade-bk-1178-3c8-a-cortex-config
2021-08-12 08:54:30 upgrade-bk-1178-3c8-a-loki
2021-08-12 12:54:37 upgrade-bk-1179-c45-a-cortex
2021-08-12 12:54:37 upgrade-bk-1179-c45-a-cortex-config
2021-08-12 12:54:37 upgrade-bk-1179-c45-a-loki
2021-08-12 12:54:37 upgrade-bk-1179-c45-a-loki-config
```

Just in case, I also checked the IAM policies and didn't see any leftover `*-s3` policies for these builds.

**Comment by nickbp** [comment] 2021-08-12 03:14
I was able to track down the cause of the left-behind buckets to an issue in the cluster uninstall code. In summary, the S3 teardown step is creating a lifecycle for everything under `system/*` but nothing else. As a result the S3 buckets will frequently have leftover content and they won't be deleted. For example here is what the buckets for the recent 1179 build look like:
```
$ aws s3 ls s3://upgrade-bk-1179-c45-a-cortex/

$ aws s3 ls s3://upgrade-bk-1179-c45-a-cortex-config/
                           PRE alertmanager/
                           PRE alerts/
                           PRE rules/

$ aws s3 ls s3://upgrade-bk-1179-c45-a-loki/
                           PRE default/
                           PRE index/

$ aws s3 ls s3://upgrade-bk-1179-c45-a-loki-config/
```

I've created a separate issue (#1258) for this leftover bucket issue. It doesn't look like it'd relate to these test failures, which are about buckets being deleted too quickly rather than not being deleted at all...

**Comment by nickbp** [comment] 2021-08-12 04:57
OK I'm thinking the problem is with the [`delete-empty-ci-buckets-aws.sh`](https://github.com/opstrace/opstrace/blob/main/ci/delete-empty-ci-buckets-aws.sh#L24) script. It will automatically try to delete any bucket that happens to be empty. In this case, loki-config is empty, so the script is able to delete it. This would then make Loki unhappy during the test, with BucketNotFound errors.

From here, I was able to find the [other build that deleted the `cortex`, `loki`, and `loki-config` buckets for 1169](https://buildkite.com/opstrace/prs/builds/5458#8bd86398-1e79-41a8-9310-62616d6bfc30/13578-14302):
```
[2021-08-10T13:38:55Z] + set +x
[2021-08-10T13:38:55Z] * Try to delete bucket: prs-bk-5456-5ed-a-loki
[2021-08-10T13:38:55Z] + aws s3api delete-bucket --bucket prs-bk-5456-5ed-a-loki
[2021-08-10T13:38:55Z]
[2021-08-10T13:38:55Z] An error occurred (BucketNotEmpty) when calling the DeleteBucket operation: The bucket you tried to delete is not empty
[2021-08-10T13:38:56Z] + true
[2021-08-10T13:38:56Z] + set +x
[2021-08-10T13:38:56Z] * Try to delete bucket: upgrade-bk-1169-d5a-a-cortex
[2021-08-10T13:38:56Z] + aws s3api delete-bucket --bucket upgrade-bk-1169-d5a-a-cortex <<<<<<<<<<<< !!! DELETED !!!
[2021-08-10T13:38:56Z] + set +x
[2021-08-10T13:38:56Z] * Try to delete bucket: upgrade-bk-1169-d5a-a-cortex-config
[2021-08-10T13:38:56Z] + aws s3api delete-bucket --bucket upgrade-bk-1169-d5a-a-cortex-config
[2021-08-10T13:38:57Z]
[2021-08-10T13:38:57Z] An error occurred (BucketNotEmpty) when calling the DeleteBucket operation: The bucket you tried to delete is not empty
[2021-08-10T13:38:57Z] + true
[2021-08-10T13:38:57Z] + set +x
[2021-08-10T13:38:57Z] * Try to delete bucket: upgrade-bk-1169-d5a-a-loki
[2021-08-10T13:38:57Z] + aws s3api delete-bucket --bucket upgrade-bk-1169-d5a-a-loki <<<<<<<<<<<< !!! DELETED !!!
[2021-08-10T13:38:58Z] + set +x
[2021-08-10T13:38:58Z] * Try to delete bucket: upgrade-bk-1169-d5a-a-loki-config
[2021-08-10T13:38:58Z] + aws s3api delete-bucket --bucket upgrade-bk-1169-d5a-a-loki-config <<<<<<<<<<<< !!! DELETED !!!
[2021-08-10T13:38:59Z] + set +x
[2021-08-10T13:38:59Z] * Try to delete bucket: prs-bk-5457-cc6-a-cortex
[2021-08-10T13:38:59Z] + aws s3api delete-bucket --bucket prs-bk-5457-cc6-a-cortex
[2021-08-10T13:39:00Z] + set +x
[2021-08-10T13:39:00Z] * Try to delete bucket: prs-bk-5457-cc6-a-cortex-config
[2021-08-10T13:39:00Z] + aws s3api delete-bucket --bucket prs-bk-5457-cc6-a-cortex-config
[2021-08-10T13:39:01Z]
[2021-08-10T13:39:01Z] An error occurred (BucketNotEmpty) when calling the DeleteBucket operation: The bucket you tried to delete is not empty
```

So I think we have a "smoking gun" here. Maybe the script could additionally filter on CI buckets with a creation date that's older than >= X days ago

**Comment by nickbp** [comment] 2021-08-13 05:27
WIP PR updating the cleanup logic here: https://github.com/opstrace/opstrace/pull/1270

From the existing logic it looks like this should only be a problem if there are >5 concurrent CI runs (20 recent buckets skipped / 4 buckets/run = 5 runs) so not super urgent but would be good to clean up.

**Comment by nickbp** [comment] 2021-08-16 06:40
#1270 was just merged with new logic to check the bucket timestamps explicitly before deleting them. The new logic waits for a CI bucket to be at least 6H old rather than waiting for a count of >20 buckets to follow it. So hopefully we won't have CI getting buckets deleted from underneath it when there's a lot of jobs going.

**Closed by nickbp** 2021-08-16 06:40 UTC
Labels: type: ci-instability
