### ISSUE TITLE
gcp: installer does not handle SQLInstance transitioning to state FAILED

### ISSUE THREAD

**Issue by jgehrcke** [opstrace/opstrace#168] opened 2020-12-14 10:11 UTC
```
[2020-12-14T00:25:04Z] 2020-12-14T00:25:04.865Z info: Ensure SQLInstance exists
[2020-12-14T00:25:05Z] 2020-12-14T00:25:05.199Z info: SQLInstance is FAILED
[2020-12-14T00:25:05Z] 2020-12-14T00:25:05.200Z error: error during cluster creation (attempt 3):
[2020-12-14T00:25:05Z] Error: Failed to create SQL Instance
[2020-12-14T00:25:05Z]     at ensureSQLInstanceExists (/snapshot/build/node_modules/@opstrace/gcp/build/cloudSQLInstance.js:0)
[2020-12-14T00:25:05Z]     at ensureSQLInstanceExists.next (<anonymous>)
[2020-12-14T00:25:05Z]     at next (/snapshot/build/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1161:27)
[2020-12-14T00:25:05Z]     at currCb (/snapshot/build/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1255:7)
[2020-12-14T00:25:05Z]     at runMicrotasks (<anonymous>)
[2020-12-14T00:25:05Z]     at processTicksAndRejections (internal/process/task_queues.js:97:5)
```
https://buildkite.com/opstrace/scheduled-main-builds/builds/1363#e84bca53-50b7-4572-bb92-e144d8b36888/223-1313

**Comment by nickbp** [comment] 2021-08-05 22:45
Might effectively be a duplicate of #293, or might just not be happening anymore. In either case this issue hasn't had any changes for approaching 8 months

**Closed by nickbp** 2021-08-05 22:45 UTC
Labels: type: bug, type: ci-instability, area: installer, area: ci

**Comment by jgehrcke** [comment] 2021-08-15 13:23
Happened again. Is just a rare one.

https://buildkite.com/opstrace/scheduled-main-builds/builds/2864#bc2e2376-0e0e-4832-89a7-7efbc245edeb/256-2010


```
[2021-08-14T21:16:41Z] 2021-08-14T21:16:41.852Z info: SQLInstance is PENDING_CREATE
[2021-08-14T21:16:52Z] 2021-08-14T21:16:52.209Z info: SQLInstance is PENDING_CREATE
[2021-08-14T21:17:02Z] 2021-08-14T21:17:02.572Z info: SQLInstance is PENDING_CREATE
[2021-08-14T21:17:12Z] 2021-08-14T21:17:12.924Z info: SQLInstance is PENDING_CREATE
[2021-08-14T21:17:23Z] 2021-08-14T21:17:23.286Z info: SQLInstance is FAILED
[2021-08-14T21:17:23Z] 2021-08-14T21:17:23.289Z debug: Creating SQLInstance failed, retrying: Error: Failed to create SQL Instance
[2021-08-14T21:17:23Z]     at ensureSQLInstanceExists (/snapshot/build/lib/gcp/build/cloudSQLInstance.js)
[2021-08-14T21:17:23Z]     at ensureSQLInstanceExists.next (<anonymous>)
[2021-08-14T21:17:23Z]     at next (/snapshot/build/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1161:27)
[2021-08-14T21:17:23Z]     at currCb (/snapshot/build/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1255:7)
[2021-08-14T21:17:23Z]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[2021-08-14T21:17:23Z] 2021-08-14T21:17:23.289Z info: Attempt 1 to create SQLInstance
...
[2021-08-14T21:43:10Z] 2021-08-14T21:43:10.545Z info: SQLInstance is FAILED
[2021-08-14T21:43:10Z] 2021-08-14T21:43:10.546Z debug: Creating SQLInstance failed, retrying: Error: Failed to create SQL Instance
[2021-08-14T21:43:10Z]     at ensureSQLInstanceExists (/snapshot/build/lib/gcp/build/cloudSQLInstance.js)
[2021-08-14T21:43:10Z]     at ensureSQLInstanceExists.next (<anonymous>)
[2021-08-14T21:43:10Z]     at next (/snapshot/build/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1161:27)
[2021-08-14T21:43:10Z]     at currCb (/snapshot/build/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1255:7)
[2021-08-14T21:43:10Z]     at runMicrotasks (<anonymous>)
```

**Comment by jgehrcke** [comment] 2021-08-15 13:27
https://github.com/opstrace/opstrace/blob/03f91eb8a57ef9b10f152d87a070df97a64d2b30/lib/gcp/src/cloudSQLInstance.ts#L115

to automatically heal that problem the right course of action is to treat this error as permanent, and to not retry. a new SQL instance creation attempt needs to be made. Like we do here: https://github.com/opstrace/opstrace/blob/ef3317cb3591cac85d1116eecc5865090391a146/lib/aws/src/rdsCluster.ts#L58

**Comment by jgehrcke** [comment] 2021-08-15 14:15
```
[2021-08-15T12:40:04Z] 2021-08-15T12:40:04.184Z info: SQLInstance is PENDING_CREATE
[2021-08-15T12:40:14Z] 2021-08-15T12:40:14.535Z info: SQLInstance is FAILED
[2021-08-15T12:40:14Z] 2021-08-15T12:40:14.537Z debug: Creating SQLInstance failed, retrying: Error: Failed to create SQL Instance
[2021-08-15T12:40:14Z]     at ensureSQLInstanceExists (/snapshot/build/lib/gcp/build/cloudSQLInstance.js)
[2021-08-15T12:40:14Z]     at ensureSQLInstanceExists.next (<anonymous>)
[2021-08-15T12:40:14Z]     at next (/snapshot/build/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1161:27)
[2021-08-15T12:40:14Z]     at currCb (/snapshot/build/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1255:7)
```
https://buildkite.com/opstrace/prs/builds/5535#08a20f3d-bd76-482c-8b4e-02526e030455/272-759
