### ISSUE TITLE
ci instability: Timeout of 120000ms exceeded in page.hover

### ISSUE THREAD

**Issue by sreis** [opstrace/opstrace#960] opened 2021-06-29 14:09 UTC
```
[2021-06-29T13:41:54Z]   1) tests/everywhere.spec.ts:25:8 › [Chromium] after auth0 authentication user should click around the entire site 
[2021-06-29T13:41:54Z]
[2021-06-29T13:41:54Z]     Timeout of 120000ms exceeded.
[2021-06-29T13:41:54Z]
[2021-06-29T13:41:54Z]     Pending operations:
[2021-06-29T13:41:54Z]       - page.hover at tests/everywhere.spec.ts:31:16
```
```
[2021-06-29T13:41:54Z]   2) tests/everywhere.spec.ts:25:8 › [WebKit] after auth0 authentication user should click around the entire site 
[2021-06-29T13:41:54Z]
[2021-06-29T13:41:54Z]     Timeout of 120000ms exceeded.
[2021-06-29T13:41:54Z]
[2021-06-29T13:41:54Z]     Pending operations:
[2021-06-29T13:41:54Z]       - page.hover at tests/everywhere.spec.ts:31:16
```

https://buildkite.com/opstrace/upgrade-tests/builds/895#b446a3ea-4985-4818-ae3d-bcc7d338c902/10352-10376

**Comment by jgehrcke** [comment] 2021-06-30 09:19
we now understand that this one here has had the same root cause as https://github.com/opstrace/opstrace/issues/959 and @terrcin believes to have fixed that in `main`. Closing this here, too.

**Closed by jgehrcke** 2021-06-30 09:19 UTC
Labels: type: ci-instability
