### ISSUE TITLE
Duplicate sample warnings in cortex ingester

### ISSUE THREAD

**Issue by sreis** [opstrace/opstrace#214] opened 2020-12-23 10:59 UTC
**Describe the bug**

We are running multiple Prometheus scraping instances that are sending duplicate data to the cortex ingesters.

```
level=warn ts=2020-12-23T09:17:57.435754493Z caller=grpc_logging.go:38 method=/cortex.Ingester/Push duration=431.348µs err="rpc error: code = Code(400) desc = user=system: series={__name__=\"cluster_quantile:apiserver_request_duration_seconds:histogram_quantile\", component=\"apiserver\", endpoint=\"https\", group=\"coordination.k8s.io\", job=\"apiserver\", namespace=\"default\", prometheus=\"system-tenant/system-prometheus\", quantile=\"0.9\", resource=\"leases\", scope=\"namespace\", service=\"kubernetes\", verb=\"GET\", version=\"v1beta1\"}, timestamp=2020-12-23T09:17:56.932Z: duplicate sample for timestamp" msg="gRPC\n"
```

This increases the number of errors when ingesting data.

![Screenshot from 2020-12-22 13-58-31](https://user-images.githubusercontent.com/495294/102989616-6f561e80-4505-11eb-9048-13311036424a.png)

This is a graph of the ingesters sample failure rate when running Prometheus with the default configuration and then with 1 replica.

**Comment by spahl** [comment] 2020-12-23 14:22
Oh nice find. This must have started when we removed the cortex HA tracker (https://cortexmetrics.io/docs/configuration/arguments/#ha-tracker). It was removed when moving to memberlist gossip instead of eyes.

Sharding prometheus is a much better solution. Thank you.

**Comment by jgehrcke** [comment] 2020-12-26 12:13
Lovely!

> We are running multiple Prometheus scraping instances

These are _system_ tenant Prometheuses, right? (Related: https://github.com/opstrace/opstrace-prelaunch/issues/1593)

This is not really a user-facing problem (system metrics collection worked as intended I suppose) but tackling this is certainly an important architecture cleanup.

**Comment by spahl** [comment] 2020-12-26 19:21
Correct this is only for the system tenant prometheus

**Comment by triclambert** [comment] 2021-01-27 18:20
Cc @nickbp

**Closed** 2022-01-11 20:26 UTC
Labels: type: bug
