### ISSUE TITLE
DNS service: may not generate a response upon expired authentication token

### ISSUE THREAD

**Issue by sreis** [opstrace/opstrace#833] opened 2021-06-04 10:56 UTC
**Describe the bug**

A user reported, in community slack, a failure creating a cluster. Logs showed a timeout error accessing the `dns-service`.

```
2021-06-04T10:24:17.161Z info: GET HTTP request to https://dns-api.opstrace.net/dns/ failed. Attempt: 1. Error: ETIMEDOUT, Timeout awaiting 'request' for 30000ms. Retry in 1.6 s. 
2021-06-04T10:24:48.792Z info: GET HTTP request to https://dns-api.opstrace.net/dns/ failed. Attempt: 2. Error: ETIMEDOUT, Timeout awaiting 'request' for 30000ms. Retry in 2.6 s. 
```

`dns-service` logs show that the given auth token had expired:
```	
2021-06-04 10:24:17	
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 212)
2021-06-04 10:24:17	
[Error [TokenValidationError]: Expiration Time (exp) claim error in the ID token; current time "Fri Jun 04 2021 10:24:17 GMT+0000 (Coordinated Universal Time)" is after expiration time "Thu Jun 03 2021 22:01:15 GMT+0000 (Coordinated Universal Time)"]
```

Opstrace CLI version `275cf649-ci`

**Expected behavior**

`dns-service` should handle the request gracefully and return a clear error message.

**Comment by sreis** [comment] 2021-06-04 10:58
Similar to #10 but in the create path.

**Comment by jgehrcke** [comment] 2021-06-04 11:55
I want to quote myself from #10:

> The authoritative response for expired credentials is a 401 response (hopefully in this case, too).

This is a bug in the DNS service; let us make sure it emits a 401 response in this case, instead of not writing an HTTP response.

**Comment by jgehrcke** [comment] 2021-06-04 11:57
Also note that on the client side the [code is there](https://github.com/opstrace/opstrace/blob/2750f917724a3d2bba340276faf55920c5663ce9/lib/dns/src/opstrace.ts#L371) to do the credential refresh upon seeing a 401 response:

```
          if (e.response?.statusCode === 401) {
            log.info("perform another login to refresh authentication state");
            this.clearAuthnState();
            await this.login();

            log.info(
              "retry the request that previously failed with a 401 response"
            );
            continue;
          }
```

**Comment by jgehrcke** [comment] 2021-06-04 11:58
> and return a clear error message.

Note that the 401 response should not contain the error detail "token expired" for security reasons. Just returning 401 is fine.

**Comment by jgehrcke** [comment] 2021-06-15 14:53
@terrcin ran into this, too: https://github.com/opstrace/opstrace/issues/884#issue-920902695

**Comment by jgehrcke** [comment] 2021-06-23 15:57
Deployed a new version of the DNS service which simpler authentication token verification. If the changes work as intended, the failure path responsible for this bug here is now gone. Closing this already, but let's keep an eye on this.

**Closed by jgehrcke** 2021-06-23 15:57 UTC
Labels: area: dns-service, backlog, type: bug
