### ISSUE TITLE
ci-instability: End-to-end alerts for default and system tenants: The expression evaluated to a falsy value

### ISSUE THREAD

**Issue by sreis** [opstrace/opstrace#1151] opened 2021-08-02 08:45 UTC
```
[2021-07-31T08:40:04Z]   1) End-to-end alert tests
[2021-07-31T08:40:04Z]        End-to-end alerts for default and system tenants:
[2021-07-31T08:40:04Z]
[2021-07-31T08:40:04Z]       AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:
[2021-07-31T08:40:04Z] 
[2021-07-31T08:40:04Z]   resources.push(
[2021-07-31T08:40:04Z]    new V1ServicemonitorResource(
[2021-07-31T08:40:04Z]      {
[2021-07-31T08:40:04Z]        apiVersion: "monitoring.coreos.com/v1",
[2021-07-31T08:40:04Z]        kind: "ServiceMonitor",
[2021-07-31T08:40:04Z]        metadata: {
[2021-07-31T08:40:04Z]          name,
[2021-07-31T08:40:04Z]          namespace,
[2021-07-31T08:40:04Z]          labels
[2021-07-31T08:40:04Z]        },
[2021-07-31T08:40:04Z]        spec: {
[2021-07-31T08:40:04Z]          jobLabel: "job", // point to 'job' label in the pod
[2021-07-31T08:40:04Z]          endpoints: [
[2021-07-31T08:40:04Z]            {
[2021-07-31T08:40:04Z]              // Spam it at 5s to get faster responses in tests
[2021-07-31T08:40:04Z]              interval: "5s",
[2021-07-31T08:40:04Z]              port: "http",
[2021-07-31T08:40:04Z]              path: "/metrics"
[2021-07-31T08:40:04Z]            }
[2021-07-31T08:40:04Z]          ],
[2021-07-31T08:40:04Z]          selector: {
[2021-07-31T08:40:04Z]            matchLabels
[2021-07-31T08:40:04Z]          }
[2021-07-31T08:40:04Z]        }
[2021-07-31T08:40:04Z]      },
[2021-07-31T08:40:04Z]      kubeConfig
[2021-07-31T08:40:04Z]    )
[2021-07-31T08:40:04Z]   )
[2021-07-31T08:40:04Z] 
[2021-07-31T08:40:04Z]       + expected - actual
[2021-07-31T08:40:04Z]
[2021-07-31T08:40:04Z]       -false
[2021-07-31T08:40:04Z]       +true
```
https://buildkite.com/opstrace/scheduled-main-builds/builds/2768#dcb12007-c38d-4d1f-a432-f39edb2ab05e

**Comment by sreis** [comment] 2021-08-02 08:48
https://buildkite.com/opstrace/scheduled-main-builds/builds/2773#a57fb179-c508-4112-893d-d951ba1f01fe

```
[2021-08-01T04:46:20Z]   1) End-to-end alert tests
[2021-08-01T04:46:20Z]        End-to-end alerts for default and system tenants:
[2021-08-01T04:46:20Z]
[2021-08-01T04:46:20Z]       AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:
[2021-08-01T04:46:20Z] 
[2021-08-01T04:46:20Z]   resources.push(
[2021-08-01T04:46:20Z]    new V1ServicemonitorResource(
[2021-08-01T04:46:20Z]      {
[2021-08-01T04:46:20Z]        apiVersion: "monitoring.coreos.com/v1",
[2021-08-01T04:46:20Z]        kind: "ServiceMonitor",
[2021-08-01T04:46:20Z]        metadata: {
[2021-08-01T04:46:20Z]          name,
[2021-08-01T04:46:20Z]          namespace,
[2021-08-01T04:46:20Z]          labels
[2021-08-01T04:46:20Z]        },
[2021-08-01T04:46:20Z]        spec: {
[2021-08-01T04:46:20Z]          jobLabel: "job", // point to 'job' label in the pod
[2021-08-01T04:46:20Z]          endpoints: [
[2021-08-01T04:46:20Z]            {
[2021-08-01T04:46:20Z]              // Spam it at 5s to get faster responses in tests
[2021-08-01T04:46:20Z]              interval: "5s",
[2021-08-01T04:46:20Z]              port: "http",
[2021-08-01T04:46:20Z]              path: "/metrics"
[2021-08-01T04:46:20Z]            }
[2021-08-01T04:46:20Z]          ],
[2021-08-01T04:46:20Z]          selector: {
[2021-08-01T04:46:20Z]            matchLabels
[2021-08-01T04:46:20Z]          }
[2021-08-01T04:46:20Z]        }
[2021-08-01T04:46:20Z]      },
[2021-08-01T04:46:20Z]      kubeConfig
[2021-08-01T04:46:20Z]    )
[2021-08-01T04:46:20Z]   )
```

**Comment by jgehrcke** [comment] 2021-08-02 13:39
@terrcin spotted this 6 days ago, noted it here: https://github.com/opstrace/opstrace/issues/1102#issuecomment-887896236

**Comment by nickbp** [comment] 2021-08-04 23:29
This looks like the same `502 Bad Gateway/nginx` root cause as we were seeing for HTTP DELETE calls in #944 and may be fixed by #1176

[from instance linked above](https://buildkite.com/opstrace/scheduled-main-builds/builds/2774#7a948280-f20e-46fd-b3d6-e49574452e55/3086-4806):
```
[2021-08-01T08:42:21Z] 2021-08-01T08:42:21.993Z [32minfo[39m: Setting up E2E alerts webhook
[2021-08-01T08:42:22Z] 2021-08-01T08:42:22.089Z [32minfo[39m: HTTP resp to POST(https://schedul-bk-2774-a90-g.opstracegcp.com/api/v1/alerts):
[2021-08-01T08:42:22Z]   status: 502
[2021-08-01T08:42:22Z]   body[:500]: <html>
[2021-08-01T08:42:22Z] <head><title>502 Bad Gateway</title></head>
[2021-08-01T08:42:22Z] <body>
[2021-08-01T08:42:22Z] <center><h1>502 Bad Gateway</h1></center>
[2021-08-01T08:42:22Z] <hr><center>nginx</center>
[2021-08-01T08:42:22Z] </body>
[2021-08-01T08:42:22Z] </html>
```

**Comment by jgehrcke** [comment] 2021-08-13 10:54
```
[2021-08-13T09:46:27Z]   21 passing (2m)
[2021-08-13T09:46:27Z]   4 pending
[2021-08-13T09:46:27Z]   1 failing
[2021-08-13T09:46:27Z]
[2021-08-13T09:46:27Z]   1) End-to-end alert tests
[2021-08-13T09:46:27Z]        End-to-end alerts for default and system tenants:
[2021-08-13T09:46:27Z]
[2021-08-13T09:46:27Z]       AssertionError [ERR_ASSERTION]: false == true
[2021-08-13T09:46:27Z]       + expected - actual
[2021-08-13T09:46:27Z]
[2021-08-13T09:46:27Z]       -false
[2021-08-13T09:46:27Z]       +true
```
https://buildkite.com/opstrace/scheduled-main-builds/builds/2850#3383ab61-62ed-4fdd-bba5-be4aa4dcad41/6-1708

**Comment by nickbp** [comment] 2021-08-18 06:11
Looks like the above 2850 failure was due to this:
```
[2021-08-13T09:44:07Z]   body[:500]: unable to store the Alertmanager config: upload s3 object: Please reduce your request rate.
```

I think there had been a fix for that at the time? Looks different from the original flake in any case.

**Closed by nickbp** 2021-08-18 06:11 UTC
Labels: type: ci-instability
