### ISSUE TITLE
Grafana promql queries fail after upgrade from 6cb91909-ci to latest main

### ISSUE THREAD

**Issue by sreis** [opstrace/opstrace#908] opened 2021-06-17 15:24 UTC
**Describe the bug**

All the promql queries are getting a 301 and a redirect to grafana/login and then fail. Yes, I've cleared the cache, cookies and browser local storage. 

![Screenshot from 2021-06-17 15-17-07](https://user-images.githubusercontent.com/495294/122426411-c2260580-cf7f-11eb-97f7-35cce688b4bb.png)

This doesn't happen with metrics although we get a 404 for the query_examplars endpoint.

![Screenshot from 2021-06-17 15-23-25](https://user-images.githubusercontent.com/495294/122426723-00bbc000-cf80-11eb-8eae-a81b7fc34f14.png)

**To Reproduce**

Upgrade Opstrace instance starting at 6cb91909-ci to latest main.

**Comment by MatApple** [comment] 2021-06-17 16:02
@sreis this shouldn't be happening but I'm guessing Grafana 8 has changed some config settings around authentication. We use Grafana in proxy mode but it appears the Grafana instance thinks it's "not in proxy mode" because it's redirecting to its own login. Perhaps there is an announcement in the Grafana 8 release notes that we missed.

Here are the config options for Grafana https://grafana.com/docs/grafana/latest/administration/configuration/

**Comment by sreis** [comment] 2021-06-17 16:07
@MatApple One strange thing is that the CI/CD cluster was upgraded this morning and does not have this problem.

**Comment by sreis** [comment] 2021-06-17 16:34
Answer to myself, the `query_examplars` that is returning a 404 is a [Prometheus endpoint](https://prometheus.io/docs/prometheus/latest/querying/api/#querying-exemplars) to correlate metrics with traces. AFAIK not yet available in Cortex.

**Comment by jgehrcke** [comment] 2021-06-17 17:37
In the very first screenshot for the very **first** 301 response it would be great to show more details:
- `Location` header of that response
- _all_ other aspects of that response so that we understand better (or _precisely_) which entity really emitted it

**Comment by MatApple** [comment] 2021-06-17 23:11
It should be noted that we turn `proxy_redirect` off, which is the same setting as nginx-ingress controller uses.

https://github.com/opstrace/opstrace/blob/5ed454ec96191dc4bea278dc019128b6848f2be6/packages/controller/src/resources/monitoring/tenants/grafanaDatasources.ts#L182

**Comment by MatApple** [comment] 2021-06-17 23:58
Treating this as related (because I think the datasource-splitter is the culprit somehow). In the `tracy` cluster (added @sreis, @jgehrcke and @nickbp), the rules endpoints in Grafana for the system tenant are also reporting 404s (one is reporting a 500 which is noteworthy)...

<img width="1918" alt="Screen Shot 2021-06-17 at 4 56 48 PM" src="https://user-images.githubusercontent.com/465022/122486058-226f7400-cf8d-11eb-8cd0-80a9847501ed.png">

**Comment by MatApple** [comment] 2021-06-18 00:22
On a fresh cluster just created with latest main, I see several interesting things that all point to the datasource-splitters.

cluster: https://mat.opstrace.io/

@jgehrcke @nickbp @sreis also added you to this cluster.

**Note we call the Loki datasource "logs" and the Cortex datasource "metrics"**

Loki datasource query returns a 200 for getting labels, but the result is empty - strange because we do have system logs with labels:
<img width="1359" alt="Screen Shot 2021-06-17 at 5 09 11 PM" src="https://user-images.githubusercontent.com/465022/122486994-02d94b00-cf8f-11eb-857b-698926bda67e.png">

Trying the Loki datasource again 5 mins later shows the request was redirected to /login and then to /grafana (this could be our own auth webhook not redirecting back to the correct place on successful login - it should redirect back to where the originating request was trying to go):
<img width="1353" alt="Screen Shot 2021-06-17 at 5 16 13 PM" src="https://user-images.githubusercontent.com/465022/122487355-f1dd0980-cf8f-11eb-8711-038a7a9e1e43.png">

Cortex datasource queries work fine for getting labels:
<img width="1852" alt="Screen Shot 2021-06-17 at 5 11 38 PM" src="https://user-images.githubusercontent.com/465022/122487057-2ac8ae80-cf8f-11eb-985b-6026fd2cae78.png">

Cortex datasource queries work fine for promql queries (range and instant) - note that exemplar queries don't work but that's expected:
<img width="2246" alt="Screen Shot 2021-06-17 at 5 12 37 PM" src="https://user-images.githubusercontent.com/465022/122487167-767b5800-cf8f-11eb-9bba-45f9d264b2d2.png">

Alerting rules for both Loki and Cortex respond with a mix of 404s and 500s (yes, alertmanager is configured for this tenant):
<img width="1873" alt="Screen Shot 2021-06-17 at 5 19 01 PM" src="https://user-images.githubusercontent.com/465022/122487466-310b5a80-cf90-11eb-9f95-720d9eca0957.png">

**Comment by MatApple** [comment] 2021-06-18 00:24
Linking in this from @sreis too https://github.com/opstrace/opstrace/pull/909

**Comment by nickbp** [comment] 2021-06-18 02:30
For viewing logs, it looks like something (not sure what) is redirecting the `/grafana/api/datasources/proxy/2/loki/*` to `/loki/*`, and the response ends up being html when the logs dashboard code is (I assume) expecting JSON.
Meanwhile the metrics queries to `/grafana/api/datasources/proxy/1/*` seem to work fine.

---

Looking at an arbitrary log query in [`nick-test`](https://system.nick-test.opstrace.io/grafana/explore?orgId=1&left=%5B%22now-1h%22,%22now%22,%22logs%22,%7B%22exemplar%22:true,%22expr%22:%22%7Bapiservice%3D%5C%22k8s_internal_local_delegation_chain_0000000002%5C%22,job%3D%5C%22apiserver%5C%22%7D%22%7D%5D) and in [`mat`](https://system.mat.opstrace.io/grafana/explore?orgId=1&left=%5B%22now-1h%22,%22now%22,%22logs%22,%7B%22exemplar%22:true,%22expr%22:%22%7Bapiservice%3D%5C%22k8s_internal_local_delegation_chain_0000000002%5C%22,job%3D%5C%22apiserver%5C%22%7D%22%7D%5D) via the network queries debug view in Firefox:
- `label` query:
  - `GET /grafana/api/datasources/proxy/2/loki/api/v1/label?[...]` gets a 301 redirect to `/loki/api/v1/label?[...]`
  - `GET /loki/api/v1/label?[...]` gets a 301 redirect to `/grafana/login`
- `query_range` query:
  - `GET /grafana/api/datasources/proxy/2/loki/api/v1/query_range?[...]` gets a 301 redirect to `/loki/api/v1/query_range?[...]`
  - `GET /loki/api/v1/label?[...]` gets a 301 redirect to `/grafana/login`
- Both queries from there:
  - `/grafana/login` gets a 302 redirect to `/grafana`
  - `/grafana` returns html when I assume the original query was returning JSON

Meanwhile the Metrics equivalent queries for [nick-test](https://system.nick-test.opstrace.io/grafana/explore?orgId=1&left=%5B%22now-1h%22,%22now%22,%22metrics%22,%7B%22exemplar%22:true,%22expr%22:%22%7Bapiservice%3D%5C%22k8s_internal_local_delegation_chain_0000000002%5C%22,job%3D%5C%22apiserver%5C%22%7D%22%7D%5D) and [mat](https://system.mat.opstrace.io/grafana/explore?orgId=1&left=%5B%22now-1h%22,%22now%22,%22metrics%22,%7B%22exemplar%22:true,%22expr%22:%22%7Bapiservice%3D%5C%22k8s_internal_local_delegation_chain_0000000002%5C%22,job%3D%5C%22apiserver%5C%22%7D%22%7D%5D) seem to be working fine:
- `POST /grafana/api/datasources/proxy/1/api/v1/labels` returns 200/json
- `POST /grafana/api/datasources/proxy/1/api/v1/query` returns 200/json
- `POST /grafana/api/datasources/proxy/1/api/v1/query_range` returns 200/json
- `GET /grafana/api/datasources/proxy/1/api/v1/label/__name__/values` returns 200/json
- ...

**Comment by nickbp** [comment] 2021-06-18 02:36
Similar notes for rules queries generated by Grafana alerts page on [mat](https://system.mat.opstrace.io/grafana/alerting/list) and [nick-test](https://system.nick-test.opstrace.io/grafana/alerting/list):
- `GET /grafana/api/prometheus/2/api/v1/rules` => 404
- `GET /grafana/api/ruler/2/api/v1/rules` => 500 with JSON response `{"message":"unexpected content type from upstream. expected YAML, got text/html"}`
- `GET /grafana/api/prometheus/1/api/v1/rules` => 404
- `GET /grafana/api/ruler/1/api/v1/rules` => 404
- `GET /grafana/api/prometheus/grafana/api/v1/rules` => 200 with response `{"status":"success","data":{"groups":[]}}`
- `GET /grafana/api/ruler/grafana/api/v1/rules` => 202 with response `{}`

**Comment by nickbp** [comment] 2021-06-18 03:29
FYI it looks like the issue is not specific to the `system` tenant. Also checked `default` tenant on `nick-test` and `staging` tenant on `mat` and they had the same behaviors for both logs and rules queries.

Checked the loki splitter pod logs and it looks like the redirects get to there:
```
192.168.55.57 - - [18/Jun/2021:03:22:35 +0000] "GET /loki/api/v1/label?from=1623964955001000000&to=1623986555001000000 HTTP/1.1" 301 0 "-" "Grafana/8.0.0"
192.168.55.57 - - [18/Jun/2021:03:22:35 +0000] "GET /loki/api/v1/query_range?direction=BACKWARD&limit=1000&query=%7Bk8s_namespace_name%3D%22foo%22%7D&start=1623982955000000000&end=1623986556000000000&step=2 HTTP/1.1" 301 0 "-" "Grafana/8.0.0"
```

The cortex splitter pod logs meanwhile show successful queries:
```
192.168.55.57 - - [18/Jun/2021:00:07:30 +0000] "POST /api/v1/labels HTTP/1.1" 200 1320 "-" "Grafana/8.0.0"
192.168.55.57 - - [18/Jun/2021:00:07:30 +0000] "GET /api/v1/label/__name__/values?start=1623953251&end=1623974851 HTTP/1.1" 200 11795 "-" "Grafana/8.0.0"
192.168.55.57 - - [18/Jun/2021:00:07:30 +0000] "GET /api/v1/metadata HTTP/1.1" 200 28170 "-" "Grafana/8.0.0"
192.168.55.57 - - [18/Jun/2021:00:07:30 +0000] "POST /api/v1/query_range HTTP/1.1" 200 8641 "-" "Grafana/8.0.0"
192.168.55.57 - - [18/Jun/2021:00:33:55 +0000] "POST /api/v1/series HTTP/1.1" 200 1908 "-" "Grafana/8.0.0"
```

For rules queries, the loki splitter pod logs show 404s and 301s depending on the endpoint (only saw these two, repeatedly):
```
192.168.55.57 - - [18/Jun/2021:02:51:48 +0000] "GET /prometheus/api/v1/rules HTTP/1.1" 404 19 "-" "Grafana/8.0.0"
192.168.55.57 - - [18/Jun/2021:02:51:48 +0000] "GET /api/prom/rules HTTP/1.1" 301 169 "-" "Grafana/8.0.0"
```

Cortex splitter rules queries are a bit different and are both 404s:
```
192.168.55.57 - - [18/Jun/2021:02:51:48 +0000] "GET /api/v1/rules HTTP/1.1" 404 19 "-" "Grafana/8.0.0"
192.168.55.57 - - [18/Jun/2021:02:51:48 +0000] "GET /rules HTTP/1.1" 404 21 "-" "Grafana/8.0.0"
```

**Comment by nickbp** [comment] 2021-06-18 04:49
[This](https://github.com/opstrace/opstrace/blob/main/packages/controller/src/resources/monitoring/tenants/grafanaDatasources.ts#L262) looks fishy:
```
            location /prometheus/api/v1/rules {
              ${generalProxyConfig}

              # Check https://github.com/opstrace/opstrace/issues/896 for more details.
              resolver ${dnsResolver};
              set $backend http://ruler.loki.svc.cluster.local:1080/prometheus/api/v1/rules$request_uri;
              proxy_pass $backend;
            }
```
Would that have resulted in upstream queries to a doubled path like `http://ruler.loki.svc.cluster.local:1080/prometheus/api/v1/rules/prometheus/api/v1/rules`? That'd at least explain the 404s when attempting to access rules. But I'm not an expert in nginx configuration.

I've made a quick attempt at fixing the redirects in the above commit (26d23f2) but I'm not sure if it works - still seeing 301s in browser console when attempting to query logs for example. From splitter pod logs:

Log data queries still failing:
```
192.168.55.57 - - [18/Jun/2021:04:26:55 +0000] "GET /loki/api/v1/label?from=1623968815500000000&to=1623990415500000000 HTTP/1.1" 301 0 "-" "Grafana/8.0.0"
192.168.55.57 - - [18/Jun/2021:04:26:55 +0000] "GET /loki/api/v1/query_range?direction=BACKWARD&limit=1000&query=%7Bk8s_namespace_name%3D%22foo%22%7D&start=1623986815000000000&end=1623990416000000000&step=5 HTTP/1.1" 301 0 "-" "Grafana/8.0.0"
```

Alerts queries still failing:
Loki
```
192.168.63.10 - - [18/Jun/2021:04:46:08 +0000] "GET /api/prom/rules HTTP/1.1" 301 169 "-" "Grafana/8.0.0"
192.168.63.10 - - [18/Jun/2021:04:46:08 +0000] "GET /prometheus/api/v1/rules HTTP/1.1" 404 19 "-" "Grafana/8.0.0"
```
Cortex
```
192.168.63.10 - - [18/Jun/2021:04:46:28 +0000] "GET /api/v1/rules HTTP/1.1" 404 19 "-" "Grafana/8.0.0"
192.168.63.10 - - [18/Jun/2021:04:46:28 +0000] "GET /rules HTTP/1.1" 404 21 "-" "Grafana/8.0.0"
```

**Comment by nickbp** [comment] 2021-06-18 05:17
This looks promising. Realized that I should just try querying the 'datasource-splitter' pods over HTTP directly. I piggybacked off of the cluster's `redis-master` pod since it has `curl` preinstalled:
```
my-machine$ kubectl exec -it -n application deployment/redis-master -- /bin/bash

redis-master$ curl -H 'X-Scope-OrgId: system' -v 'http://grafana-datasource-splitter-loki.system-tenant.svc.cluster.local/loki/api/v1/query_range?direction=BACKWARD&limit=1000&query=%7Bk8s_namespace_name%3D%22foo%22%7D&start=1623986806000000000&end=1623990407000000000&step=5'
[...]
> GET /loki/api/v1/query_range?direction=BACKWARD&limit=1000&query=%7Bk8s_namespace_name%3D%22foo%22%7D&start=1623986806000000000&end=1623990407000000000&step=5 HTTP/1.1
> Host: grafana-datasource-splitter-loki.system-tenant.svc.cluster.local
> User-Agent: curl/7.64.0
> Accept: */*
> X-Scope-OrgId: system
> 
< HTTP/1.1 301 Moved Permanently
< Server: nginx/1.20.1
< Date: Fri, 18 Jun 2021 05:10:52 GMT
< Content-Length: 0
< Connection: keep-alive
< Location: /loki/api/v1/query_range?direction=BACKWARD&limit=1000&query=%7Bk8s_namespace_name%3D%22foo%22%7D&start=1623986806000000000&end=1623990407000000000&step=5
< 
```

So it looks like the mystery redirects are coming from the splitter. In this case the redirect doesn't even make sense, it's giving a redirect location that matches the query we just made.

Summary:
- loki logs are failing to query with invalid 301 redirects, while cortex metrics appear fine
- both loki and cortex rules are failing to query with 404s and invalid 301s
- this all seems to be related to the new grafana-datasource-splitter-[cortex/loki] services, which are acting as an adapter between grafana (client) and cortex/loki (proxied server), and are running nginx internally

**Comment by jgehrcke** [comment] 2021-06-18 11:11
Thanks @nickbp for the great debugging above. Based on that, I think I understand quite a lot already.

In the Loki query flow through Grafana the latest item in the chain (Loki querier) sees something in the request that makes it emit a redirect to 'clean up the request' -- this could be something like a double slash somewhere in the incoming request URL.

> So it looks like the mystery redirects are coming from the splitter. In this case the redirect doesn't even make sense, it's giving a redirect location that matches the query we just made.

I think you've shown two really important points with that mystery:
- The response is generated by upstream (Loki querier)
- The request URL as seen by upstream (Loki querier) is _different_ from the one that it wants to redirect to. We don't see _that_ URL (the one that the splitter proxy presents to the Loki querier)!

When it does that redirect, it is not aware of how the outest element (completely other side of the chain) actually reached it -- it's not aware of the `/grafana/api/datasources/proxy/2` part of the URL.

Transparent rewriting of the `Location` header value on the way 'back' to the outest HTTP client is something that a reverse proxy can do. We disabled that functionality in the datasource splitter proxy ([proxy_redirect](http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_redirect) off). The Grafana proxy could do it, but probably also does _not_.

Therefore, the `Location` header as seen by the outest http client does not contain `/grafana/api/datasources/proxy/2`.

That makes it entirely plausible that the redirect pushes the outest HTTP client (the browser) into a direction that's completely bogus and results in all kinds of funny artifacts (like: 404 response, or redirection to login).

Conclusion: clean up nginx config, really understand every single slash.

**Comment by jgehrcke** [comment] 2021-06-21 12:47
I think we can close this for now.

**Closed by jgehrcke** 2021-06-21 12:47 UTC
